server:
  port: 14005

spring:
  application:
    name: assessment-service

  rabbitmq:
    host: localhost
    port: 5672
    username: postgres
    password: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/questionarium
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
    level:
        org:
            springframework:
                security: TRACE