services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/sql/:/docker-entrypoint-initdb.d/:rw
    ports:
      - "5432:5432"
    networks:
      - questionarium-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - questionarium-network

volumes:
  postgres-data:

networks:
  questionarium-network:
    name: questionarium-network

