server:
  port: 14000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG

# Configuração dos microserviços
services:
  auth:
    host: ${AUTH_SERVICE_URL}
  user:
    host: ${USER_SERVICE_URL}
  email:
    host: ${EMAIL_SERVICE_URL}
  question:
    host: ${QUESTION_SERVICE_URL}
  assessment:
    host: ${ASSESSMENT_SERVICE_URL}
  report:
    host: ${REPORT_SERVICE_URL}
  answer-sheet:
    host: ${ANSWER_SHEET_SERVICE_URL}
  ai:
    host: ${AI_SERVICE_URL}
  frontend:
    host: ${FRONTEND_URL}